ChartValues:
  service:
    selector:
      component: yunikorn-scheduler
    type: LoadBalancer
    ports:
    - port: 9889
      targetPort: 9889
HelmChartPath: helm
RuntimeType: Kubernetes
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: linziqiaolzq/quickstart-yunikorn
RegionId: cn-hangzhou
OutputType: HelmNotes
Owner: linziqiaolzq
Branch: main
Platform: github
